# Generated by Django 3.2.4 on 2021-06-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='link',
            field=models.SlugField(blank=True, help_text='Leave empty to auto create or add custom', max_length=30, null=True, unique=True),
        ),
    ]
