# Generated by Django 3.2.4 on 2021-06-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='facebook_page_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram_page_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('Open for all', 'Open for all'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='staff_in_charge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.faculty'),
        ),
        migrations.AddField(
            model_name='event',
            name='topic',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
