# Generated by Django 3.2.4 on 2021-06-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210617_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='markdown_content',
            field=models.TextField(blank=True, help_text='Markdown content if any', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='facebook_page_link',
            field=models.URLField(blank=True, help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='instagram_page_link',
            field=models.URLField(blank=True, help_text='Optional', null=True),
        ),
    ]
