# Generated by Django 3.2.4 on 2021-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_course_markdown_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
