# Generated by Django 3.2.4 on 2021-06-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20210617_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='email',
            field=models.EmailField(default='test@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='faculty',
            name='phone_number',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
