# Generated by Django 3.2.4 on 2021-06-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_alter_alumni_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='web.batch'),
        ),
    ]
