# Generated by Django 3.2.4 on 2021-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20210623_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(help_text='Select multiple tags related to the image', to='web.Tag'),
        ),
    ]
