# Generated by Django 3.2.4 on 2021-06-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_gallery_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='date',
            field=models.DateField(help_text='Images will be sorted on the basis of the dates.', null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Select multiple tags related to the image', to='web.Tag'),
        ),
    ]
