# Generated by Django 3.2.6 on 2021-08-11 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20210811_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iphash',
            old_name='creation_time',
            new_name='visit_time',
        ),
    ]
