# Generated by Django 4.0 on 2021-12-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='reg_fee',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
