# Generated by Django 4.0 on 2021-12-21 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0032_dashboardnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
    ]
