# Generated by Django 4.0 on 2021-12-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_alter_student_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.faculty'),
        ),
    ]
