# Generated by Django 4.0 on 2021-12-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_subevents_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Initiated', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
