# Generated by Django 4.0 on 2021-12-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_alter_order_status_alter_order_transaction_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Initiated', max_length=10),
        ),
    ]
