# Generated by Django 4.0 on 2021-12-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_remove_order_mode_remove_order_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='events_registered',
        ),
        migrations.AddField(
            model_name='transaction',
            name='events_registered',
            field=models.ManyToManyField(blank=True, to='web.SubEvents'),
        ),
    ]
