# Generated by Django 4.0 on 2021-12-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_remove_order_events_registered_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Registration',
        ),
    ]
