# Generated by Django 4.0 on 2021-12-24 17:57

import core.apps.web.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.CharField(blank=True, help_text='Leave empty to auto create or add custom', max_length=50, null=True)),
                ('image_url', models.URLField()),
                ('description', models.TextField()),
                ('markdown_content', models.TextField(blank=True, help_text='Markdown content if any', null=True)),
                ('student_count', models.IntegerField(default=35)),
                ('language', models.CharField(default='English/Malayalam', max_length=40)),
                ('duration', models.CharField(default='3 years', max_length=15)),
                ('first_sem_syllabus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None)),
                ('second_sem_syllabus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None)),
                ('third_sem_syllabus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None)),
                ('fourth_sem_syllabus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None)),
                ('fifth_sem_syllabus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None)),
                ('sixth_sem_syllabus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.URLField(null=True)),
                ('link', models.CharField(blank=True, help_text='Leave empty to auto create or add custom', max_length=100, null=True)),
                ('designation', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='IpHash',
            fields=[
                ('hash', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('visit_time', models.DateTimeField(default=core.apps.web.models.time_now)),
            ],
            options={
                'verbose_name': 'Site Visitor',
            },
        ),
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional', max_length=30, null=True)),
                ('description', models.TextField(blank=True, help_text='Optional', null=True)),
                ('image', models.ImageField(upload_to='img/popups')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(help_text='Messages will be sorted on basis of this date')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('date', models.DateField(help_text='Images will be sorted on the basis of the dates.', null=True)),
                ('description', models.CharField(blank=True, max_length=30, null=True)),
                ('tags', models.ManyToManyField(blank=True, help_text='Select multiple tags related to the image', to='web.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumni', to='web.batch')),
            ],
        ),
    ]
