# Generated by Django 3.2.4 on 2021-06-18 14:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='first_year_syllabus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='second_year_syllabus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='course',
            name='third_year_syllabus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, help_text='Add multiple module names separated by comma', null=True, size=None),
        ),
    ]
