# Generated by Django 3.2.4 on 2021-06-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210618_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='markdown_content',
            field=models.TextField(blank=True, help_text='Markdown content if any', null=True),
        ),
    ]
