# Generated by Django 3.2.4 on 2021-06-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_faculty_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='quote',
        ),
        migrations.AddField(
            model_name='alumni',
            name='date',
            field=models.DateTimeField(help_text='Images will be sorted on the basis of the dates.', null=True),
        ),
    ]
