# Generated by Django 4.2.6 on 2024-12-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0004_remove_faculty_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="is_student_coordinator",
            field=models.BooleanField(
                default=False,
                help_text="If checked will not show up in the Faculty section",
            ),
        ),
    ]
