# Generated by Django 4.2.6 on 2025-09-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0005_alter_faculty_is_student_coordinator"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="popup",
            name="image",
        ),
        migrations.AddField(
            model_name="popup",
            name="image_url",
            field=models.URLField(default="https://google.com", help_text="Required"),
            preserve_default=False,
        ),
    ]
