# Generated by Django 3.2.4 on 2021-06-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumni',
            new_name='Gallery',
        ),
    ]
