# Generated by Django 3.2.6 on 2021-08-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_iphash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='img/popups')),
            ],
        ),
        migrations.AlterField(
            model_name='iphash',
            name='hash',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
