# Generated by Django 3.2.6 on 2021-08-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_rename_creation_time_iphash_visit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='description',
            field=models.TextField(blank=True, help_text='Optional', null=True),
        ),
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(blank=True, help_text='Optional', max_length=30, null=True),
        ),
    ]
