# Generated by Django 3.2.6 on 2021-12-20 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20210811_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iphash',
            options={'verbose_name': 'Site Visitor'},
        ),
    ]
