# Generated by Django 4.0 on 2021-12-21 06:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('starting_time', models.DateTimeField()),
                ('ending_time', models.DateTimeField()),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
