# Generated by Django 4.0 on 2021-12-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0024_subevents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
