# Generated by Django 4.0 on 2021-12-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_student_email_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='access_token',
            field=models.CharField(default='asdasdasdasDA', max_length=100),
            preserve_default=False,
        ),
    ]
