# Generated by Django 4.0 on 2021-12-21 08:01

from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_student_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=web.models.generate_order_id, max_length=9, primary_key=True, serialize=False)),
                ('payment_amount', models.IntegerField()),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_token', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=7)),
                ('events_registered', models.ManyToManyField(blank=True, to='web.SubEvents')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student')),
            ],
        ),
    ]
