# Generated by Django 4.0 on 2021-12-22 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_token',
        ),
        migrations.AddField(
            model_name='order',
            name='total_value',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=8, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='INITIATED', max_length=15)),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.IntegerField(default=0)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.order')),
            ],
        ),
    ]
