# Generated by Django 4.0 on 2021-12-22 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_rename_order_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='order',
            new_name='registration',
        ),
    ]
