# Generated by Django 4.0 on 2021-12-22 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0040_rename_order_transaction_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_event', to='web.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_student', to='web.student'),
        ),
    ]
