# Generated by Django 4.0 on 2021-12-22 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_alter_registration_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='events_registered',
            new_name='events_selected',
        ),
    ]
