# Generated by Django 4.0 on 2021-12-22 07:01

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0043_rename_events_registered_transaction_events_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='paytm_transaction_id',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.CharField(default=web.models.generate_transaction_id, max_length=9, primary_key=True, serialize=False),
        ),
    ]
