# Generated by Django 4.0 on 2021-12-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0044_transaction_paytm_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevents',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.event'),
        ),
    ]
