# Generated by Django 4.0 on 2021-12-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0046_alter_transaction_bank_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardnotification',
            name='author',
        ),
    ]
