# Generated by Django 4.0 on 2021-12-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0047_remove_dashboardnotification_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='completed_profile_setup',
            field=models.BooleanField(default=False),
        ),
    ]
