# Generated by Django 4.0 on 2021-12-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0049_rename_date_event_start_date_event_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open_date',
            field=models.DateTimeField(null=True),
        ),
    ]
