# Generated by Django 4.2.6 on 2025-08-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image_url",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
