# Generated by Django 4.2.6 on 2025-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_student_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="image_url",
            field=models.URLField(null=True),
        ),
    ]
