# Generated by Django 4.2.6 on 2023-11-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_program_reg_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
