# Generated by Django 4.2.6 on 2023-11-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_student_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='special_message',
            field=models.TextField(blank=True, help_text='Special message to send in email if any', null=True),
        ),
    ]
