# Generated by Django 4.0 on 2021-12-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_registration_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registered_programs',
            field=models.ManyToManyField(blank=True, to='dashboard.Program'),
        ),
    ]
