# Generated by Django 4.2.6 on 2023-12-02 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_event_special_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 12, 2, 21, 20, 58, 560518)),
            preserve_default=False,
        ),
    ]
