# Generated by Django 4.0 on 2021-12-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_student_registered_programs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='total_value',
        ),
    ]
