# Generated by Django 4.2.6 on 2023-12-02 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_student_anomalous_update_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='listing_order',
            field=models.IntegerField(default=0),
        ),
    ]
