# Generated by Django 4.0 on 2021-12-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_registration_total_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='raw_response',
            field=models.TextField(null=True),
        ),
    ]
