# Generated by Django 4.2.6 on 2023-12-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_event_listing_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('site_instagram', models.URLField(blank=True, help_text='Please enter valid instagram profile url', max_length=100, null=True)),
                ('site_external_link', models.URLField(blank=True, help_text='Please enter valid website url', max_length=100, null=True)),
                ('event_support_email', models.CharField(blank=True, max_length=100, null=True)),
                ('event_support_whatsapp', models.CharField(blank=True, help_text='Please enter valid whatsapp number', max_length=10, null=True)),
                ('event_support_instagram', models.CharField(blank=True, help_text="Please enter valid instagram id (exclude '@')", max_length=20, null=True)),
                ('youtube_video_box_title', models.CharField(blank=True, max_length=30, null=True)),
                ('youtube_video_embed_code', models.CharField(blank=True, help_text='Make sure video embedding is allowed in youtube console', max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
