# Generated by Django 4.0 on 2021-12-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_transaction_raw_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(default=0.0),
        ),
    ]
