# Generated by Django 4.2.6 on 2023-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_sitesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='support_enabled',
            field=models.BooleanField(default=False, help_text='Select if support option needs to be enabled'),
        ),
    ]
