# Generated by Django 4.0 on 2021-12-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_transaction_mail_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='qr',
            field=models.URLField(blank=True, null=True),
        ),
    ]
