# Generated by Django 4.0 on 2021-12-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_registration_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_registrations', to='dashboard.student'),
        ),
    ]
