# Generated by Django 4.2.6 on 2024-12-23 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_program_registration_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="is_student",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="reg_fee",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
