# Generated by Django 4.0 on 2021-12-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_registration_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='events_selected_tuple',
            field=models.JSONField(null=True),
        ),
    ]
