# Generated by Django 4.2.6 on 2024-12-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_student_is_student_alter_program_reg_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="custom_registration_button_link",
            field=models.URLField(blank=True, help_text="Optional", null=True),
        ),
    ]
