# Generated by Django 4.2.6 on 2024-12-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0012_event_custom_registration_button_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesetting",
            name="custom_event_page_name",
            field=models.CharField(
                blank=True,
                help_text="[Optional]: This will change the default Event page links",
                max_length=10,
                null=True,
            ),
        ),
    ]
