# Generated by Django 4.0 on 2021-12-26 19:04

import core.apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_events_selected_tuple_transaction_events_selected_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='events_selected_json',
            field=models.JSONField(default=core.apps.dashboard.models.default_json, null=True),
        ),
    ]
