# Generated by Django 4.2.6 on 2024-12-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_sitesetting_custom_event_page_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="custom_event_page_name",
            field=models.CharField(
                blank=True,
                help_text="[Optional]: This will change the default Event page links",
                max_length=12,
                null=True,
            ),
        ),
    ]
