# Generated by Django 4.2.6 on 2025-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0014_alter_sitesetting_custom_event_page_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
