# Generated by Django 4.0 on 2021-12-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_program_ending_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='made_successful_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
