# Generated by Django 4.0 on 2021-12-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_registration_made_successful_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='failure_msg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
