# Generated by Django 4.0 on 2021-12-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_transaction_failure_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='failure_msg',
            field=models.TextField(null=True),
        ),
    ]
