# Generated by Django 4.0 on 2021-12-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_transaction_failure_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='order',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
