# Generated by Django 4.0 on 2021-12-29 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_slideshow_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDay',
            fields=[
                ('date', models.DateTimeField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('default_display', models.CharField(blank=True, help_text='Will be display if no program is assigned', max_length=200, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.eventday')),
                ('programs', models.ManyToManyField(blank=True, to='dashboard.Program')),
            ],
        ),
        migrations.AddField(
            model_name='eventday',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.event'),
        ),
    ]
