# Generated by Django 4.0 on 2021-12-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_eventday_remove_event_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventday',
            name='date',
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
