# Generated by Django 4.0 on 2021-12-31 17:11

import core.apps.dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='creation_time',
            field=models.DateTimeField(default=core.apps.dashboard.models.time_now),
        ),
    ]
