# Generated by Django 4.0 on 2022-01-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_transaction_creation_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-creation_time',)},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='events_selected',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='dashboard.Program'),
        ),
    ]
