# Generated by Django 4.0 on 2022-01-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
