# Generated by Django 4.0 on 2022-01-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_program_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='spot',
            field=models.BooleanField(default=False),
        ),
    ]
