# Generated by Django 4.0 on 2022-01-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_transaction_spot'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='physical_id_allotted',
            field=models.BooleanField(default=False),
        ),
    ]
