# Generated by Django 4.0 on 2022-01-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_registration_physical_id_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventschedule',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
