# Generated by Django 4.0 on 2022-01-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_eventschedule_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventschedule',
            name='default_display',
            field=models.CharField(blank=True, help_text='Will be displayed if no program is assigned', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventschedule',
            name='venue',
            field=models.CharField(blank=True, help_text='Will be displayed for default', max_length=100, null=True),
        ),
    ]
