# Generated by Django 4.0 on 2022-01-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_eventschedule_default_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='venue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
