# Generated by Django 4.0.1 on 2022-01-17 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_rename_registration_open_program_online_registration_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='facebook_page_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='instagram_page_link',
        ),
        migrations.RemoveField(
            model_name='event',
            name='twitter_link',
        ),
    ]
