# Generated by Django 4.0.1 on 2022-01-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_event_facebook_page_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='skill_level',
        ),
        migrations.RemoveField(
            model_name='event',
            name='status',
        ),
    ]
