# Generated by Django 4.0.1 on 2022-02-07 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_remove_event_skill_level_remove_event_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionProgramRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_given', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_relation', to='dashboard.program')),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='events_selected',
        ),
        migrations.AddField(
            model_name='transaction',
            name='programs_selected',
            field=models.ManyToManyField(blank=True, related_name='transactions', through='dashboard.TransactionProgramRelation', to='dashboard.Program'),
        ),
        migrations.AddField(
            model_name='transactionprogramrelation',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_relation', to='dashboard.transaction'),
        ),
    ]
