# Generated by Django 4.2.6 on 2023-10-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_transactionprogramrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='access_token',
            field=models.CharField(max_length=300),
        ),
    ]
