# Generated by Django 4.2.6 on 2023-10-16 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_student_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='registrar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.student'),
        ),
    ]
